# -*- coding: utf-8 -*-
"""binary_multiplication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19k6lXw4ho81AtTmC3kglKgjmi7b0HtaD
"""

import booths_algorithm
import columncompression